name: ci

on:
  workflow_call:
    inputs:
      env:
        description: 'Target SDLC environment'
        required: true
        type: string

concurrency:
  group: ${{ inputs.env }}
  cancel-in-progress: true
        
jobs:
  build-and-test:
    name: build and test on workflow call
    runs-on: ubuntu-latest

    steps:
      - name: Build the code
        run: |
          echo "starting code build"
          sleep 2m
          echo "finish code build"
    
